In [139]:
import pandas as pd

In [140]:
from sklearn.datasets import load_iris
iris = load_iris()

In [141]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [142]:
df = pd.DataFrame(iris.data)

In [143]:
df['target']=iris.target

In [144]:
x = df.drop('target',axis='columns')
y = df.target

In [145]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

In [146]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2)

In [147]:
from sklearn.model_selection import cross_val_score
a = cross_val_score(LogisticRegression(),x,y,cv=10)

D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_o

In [148]:
b = cross_val_score(SVC(C=5),x,y,cv=5)

In [149]:
c = cross_val_score(tree.DecisionTreeClassifier(),x,y,cv=5)

In [150]:
d = cross_val_score(RandomForestClassifier(n_estimators=20),x,y,cv=5)

In [151]:
a.mean()

0.9733333333333334

In [152]:
b.mean()

0.9866666666666667

In [153]:
c.mean()

0.9666666666666668

In [154]:
d.mean()

0.96

In [116]:
import pandas as pd

In [117]:
dt = pd.read_csv('canada-per-capi.csv')
dt

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [119]:
x = dt.drop('price',axis='columns')
y = dt.price

In [120]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

In [121]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2)

In [125]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),x,y,cv=2)

ValueError: n_splits=2 cannot be greater than the number of members in each class.

In [123]:
a.predict([[2600]])

AttributeError: 'numpy.ndarray' object has no attribute 'predict'

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Fare','Cabin','Embarked'], axis='columns', inplace=True)

In [5]:
df.Age = df.Age.fillna(df.Age.median())

In [10]:
df.Sex.unique()

array(['male', 'female'], dtype=object)

In [12]:
df.Sex.replace({'male':'1', 'female':'0'}, inplace=True)

In [14]:
x = df.drop('Survived', axis='columns')
y = df.Survived

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [78]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

In [79]:
from sklearn.model_selection import cross_val_score
a = cross_val_score(LogisticRegression(),x_train, y_train, cv=5)
a

array([0.77622378, 0.74125874, 0.76056338, 0.75352113, 0.84507042])

In [80]:
b = cross_val_score(SVC(),x_train, y_train, cv=5)
b

array([0.64335664, 0.62937063, 0.61267606, 0.61971831, 0.61267606])

In [81]:
c = cross_val_score(tree.DecisionTreeClassifier(),x_train, y_train, cv=5)
c

array([0.74825175, 0.76223776, 0.78873239, 0.81690141, 0.84507042])

In [82]:
d = cross_val_score(RandomForestClassifier(n_estimators=50),x_train, y_train, cv=5)
d

array([0.75524476, 0.76223776, 0.8028169 , 0.81690141, 0.86619718])

In [83]:
a.mean()

0.7753274894119965

In [84]:
b.mean()

0.6235595390524968

In [85]:
c.mean()

0.7922387471683245

In [86]:
d.mean()

0.8006796020880529

In [2]:
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=.3)

In [8]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9425925925925925

In [9]:
sv = SVC()
sv.fit(x_train, y_train)
sv.score(x_test, y_test)

0.9796296296296296

In [10]:
de = tree.DecisionTreeClassifier()
de.fit(x_train, y_train)
de.score(x_test, y_test)

0.8351851851851851

In [11]:
ran = RandomForestClassifier()
ran.fit(x_train, y_train)
ran.score(x_test, y_test)

0.9666666666666667

In [35]:
from sklearn.model_selection import cross_val_score
a = cross_val_score(LogisticRegression(), digits.data, digits.target, cv=10)
a

D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_o

array([0.90555556, 0.96111111, 0.87777778, 0.92777778, 0.94444444,
       0.96666667, 0.95      , 0.93854749, 0.87150838, 0.93854749])

In [67]:
from sklearn.model_selection import cross_val_score
b = cross_val_score(SVC(C=10), digits.data, digits.target, cv=10)
b

array([0.96666667, 1.        , 0.95      , 0.98888889, 0.99444444,
       0.98888889, 1.        , 0.99441341, 0.96648045, 0.96648045])

In [37]:
from sklearn.model_selection import cross_val_score
c = cross_val_score(tree.DecisionTreeClassifier(),digits.data, digits.target, cv=10)
c

array([0.78888889, 0.83333333, 0.84444444, 0.78888889, 0.78333333,
       0.87777778, 0.9       , 0.80446927, 0.77653631, 0.82681564])

In [53]:
from sklearn.model_selection import cross_val_score
d = cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target, cv=10)
d

array([0.91111111, 0.97777778, 0.94444444, 0.91111111, 0.95      ,
       0.96666667, 0.97222222, 0.95530726, 0.91061453, 0.94413408])

In [39]:
a.mean()

0.928193668528864

In [68]:
b.mean()

0.9816263190564867

In [69]:
c.mean()

0.8224487895716945

In [70]:
d.mean()

0.9443389199255121

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('IRIS.csv')
df.rename(columns={'sepal_length':'sl','sepal_width':'sw','petal_length':'pl','petal_width':'pw'}, inplace=True)
df

sl   sw   pl   pw         species
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.species = le.fit_transform(df[['species']])

D:\jupyter\mynumpy\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [57]:
x = df.drop('species', axis='columns')
y = df.species

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

In [59]:
from sklearn.model_selection import cross_val_score
a = cross_val_score(LogisticRegression(), x_train, y_train, cv=10 )

D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\jupyter\mynumpy\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_o

In [75]:
b = cross_val_score(SVC(C=5),x_train, y_train, cv=10)

In [61]:
c = cross_val_score(tree.DecisionTreeClassifier(), x_train, y_train, cv=10)

In [62]:
d = cross_val_score(RandomForestClassifier(n_estimators=100), x_train, y_train, cv=10)

In [63]:
a.mean()

0.9583333333333333

In [76]:
b.mean()

0.9916666666666666

In [65]:
c.mean()

0.9499999999999998

In [66]:
d.mean()

0.9583333333333333

In [17]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [18]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,0]):
    print(train_index, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
