#                        Welcome to numpy

In [1]:
import numpy as np

In [2]:
arr = np.array(([1,2,3],[4,5,"kashif"],[7,8,9]))

In [3]:
arr

array([['1', '2', '3'],
       ['4', '5', 'kashif'],
       ['7', '8', '9']], dtype='<U11')

In [4]:
arr[1,2]

'kashif'

In [5]:
arr

array([['1', '2', '3'],
       ['4', '5', 'kashif'],
       ['7', '8', '9']], dtype='<U11')

In [6]:
arr.dtype

dtype('<U11')

In [7]:
arr.size

9

In [8]:
arr.shape

(3, 3)

In [9]:
zeros = np.zeros((5,5))

In [10]:
zeros[0,2]=3

In [11]:
zeros

array([[0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.array({1,2,3,4,5})

array({1, 2, 3, 4, 5}, dtype=object)

In [13]:
zeros = np.zeros((2,3))

In [14]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
rng = np.arange(10)

In [16]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
lspace = np.linspace(1,15,8)

In [18]:
lspace

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

In [19]:
emp = np.empty((2,3))

In [20]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

In [23]:
ide = np.identity(5)

In [24]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
rng = np.arange(33)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [27]:
rng = rng.reshape(3,11)

In [28]:
rng

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [29]:
import numpy as np

In [30]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [31]:
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
ar.sum(axis=0)

array([12,  8,  9])

In [34]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [35]:
ar = np.array(x)

In [4]:
import numpy as np

In [5]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
arr = np.array(x)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.sum(1)

array([ 6, 15, 24])

In [41]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.flat

In [44]:
for a in arr.flat:
    print(a)

1
2
3
4
5
6
7
8
9


In [45]:
arr.dtype

dtype('int32')

In [46]:
arr.nbytes

36

In [47]:
arr.argmax()

8

In [48]:
arr.argmin()

0

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr.argmin()

0

In [51]:
arr.argmax()

8

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.argmax(0)

array([2, 2, 2], dtype=int64)

In [54]:
arr.argmax(1)

array([2, 2, 2], dtype=int64)

In [55]:
arr.argmax(0)

array([2, 2, 2], dtype=int64)

In [56]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [61]:
arr[1,1]=5

In [62]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr.argsort(1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [64]:
arr.argsort(1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [65]:
arr.argsort(0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [66]:
print("Kashif Malik")

Kashif Malik


In [11]:
import numpy as np

In [26]:
brr = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int8)

In [27]:
brr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [28]:
brr.dtype

dtype('int8')

In [80]:
brr.shape

(3, 3)

In [81]:
brr.size

9

In [88]:
one = np.empty((3,5))

In [89]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
emp = np.empty((3,5))

In [35]:
emp

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
one = np.ones((4,5))

In [41]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
one.shape

(4, 5)

In [43]:
one.reshape(2,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
one.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [50]:
one.flat

In [54]:
for a in one.flat:
    print(a)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [55]:
one.ndim

2

In [56]:
one.nbytes

160

In [123]:
ar1 = np.array([[1,2,2,3],[4,5,5,6],[5,8,5,9]], np.int64)

In [124]:
len(ar1)

3

In [73]:
ar2 = np.array([[1,2,3],[2,3,4],[1,2,3]])

In [74]:
ar1 + ar2

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [75]:
[344, 555] + [320, 550]

[344, 555, 320, 550]

In [76]:
344+200

544

In [77]:
5*2

10

In [78]:
ar1 * ar2

array([[ 1,  4,  9],
       [ 8, 15, 24],
       [ 7, 16, 27]])

In [79]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [81]:
ar1.sum()

45

In [83]:
ar1.max()

9

In [84]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
ar1.min()

1

In [88]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
np.where(ar1>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [94]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
np.where(ar1>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [98]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
len(ar1)

3