In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('homepricess.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [8]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [9]:
new_dummies = pd.concat([df, dummies], axis='columns')
new_dummies

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [10]:
new_dummies.drop(['town','west windsor'],axis='columns', inplace=True)

In [11]:
new_dummies

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [12]:
x = new_dummies.drop('price', axis='columns')
x

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [13]:
y = new_dummies.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [14]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [15]:
model.predict([[3400,0,0]])

D:\jupyter\mynumpy\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [16]:
model.predict([[2800,0,1]])

D:\jupyter\mynumpy\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [17]:
import joblib
joblib.dump(model, 'dummy')

['dummy']

In [19]:
a = joblib.load('dummy')
a

LinearRegression()

# one hot coding

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [18]:
x = dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [19]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000], dtype=int64)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv')
df

match dayofweek        match_time      home_team     away_team  home_xg  \
0       1       Sun  20-11-2022 19:00          Qatar       Ecuador      0.3   
1       2       Mon  21-11-2022 16:00        England       IR Iran      2.1   
2       3       Mon  21-11-2022 19:00        Senegal   Netherlands      0.9   
3       4       Mon  21-11-2022 22:00  United States         Wales      0.8   
4       5       Tue  22-11-2022 13:00      Argentina  Saudi Arabia      2.2   
..    ...       ...               ...            ...           ...      ...   
57     58       Fri  09-12-2022 22:00    Netherlands     Argentina      0.6   
58     59       Sat  10-12-2022 18:00        Morocco      Portugal      1.4   
59     60       Sat  10-12-2022 22:00        England        France      2.4   
60     61       Tue  13-12-2022 22:00      Argentina       Croatia      NaN   
61     62       Wed  14-12-2022 22:00         France       Morocco      NaN   

    away_xg        score  attendance                          venue  ...  \
0       1.2          0–2     67372.0                Al Bayt Stadium  ...   
1       1.4          6–2     45334.0  Khalifa International Stadium  ...   
2       0.7          0–2     41721.0             Al Thumama Stadium  ...   
3       1.5          1–1     43418.0          Ahmed bin Ali Stadium  ...   
4       0.1          1–2     88012.0          Lusail Iconic Stadium  ...   
..      ...          ...         ...                            ...  ...   
57      1.9  (3) 2–2 (4)     88235.0          Lusail Iconic Stadium  ...   
58      0.9          1–0     44198.0             Al Thumama Stadium  ...   
59      0.9          1–2     68895.0                Al Bayt Stadium  ...   
60      NaN          NaN         NaN          Lusail Iconic Stadium  ...   
61      NaN          NaN         NaN                Al Bayt Stadium  ...   

   away_clearances home_offsides away_offsides home_gks away_gks  \
0              7.0           3.0           4.0      4.0      7.0   
1             23.0           2.0           2.0      5.0      5.0   
2             16.0           2.0           1.0      6.0     10.0   
3             31.0           1.0           1.0      5.0     10.0   
4             26.0          10.0           1.0      3.0      9.0   
..             ...           ...           ...      ...      ...   
57            20.0           1.0           2.0      9.0      9.0   
58             3.0           2.0           2.0     12.0      9.0   
59            16.0           1.0           2.0      9.0      5.0   
60             NaN           NaN           NaN      NaN      NaN   
61             NaN           NaN           NaN      NaN      NaN   

   home_throw_ins away_throw_ins  home_long_balls  away_long_balls   age  
0            20.0           17.0             51.0             70.0  20.0  
1            18.0           17.0             87.0             50.0  20.0  
2            17.0           28.0             64.0             66.0  30.0  
3            22.0           25.0             56.0             90.0  40.0  
4            24.0           13.0             55.0             59.0  25.0  
..            ...            ...              ...              ...   ...  
57           29.0           19.0             93.0             57.0  28.0  
58           11.0           27.0             61.0             73.0  28.0  
59           16.0           14.0             61.0             62.0  28.0  
60            NaN            NaN              NaN              NaN   NaN  
61            NaN            NaN              NaN              NaN   NaN  

[62 rows x 54 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['label']=le.fit_transform(df.home_team)

In [9]:
df

match dayofweek        match_time      home_team     away_team  home_xg  \
0       1       Sun  20-11-2022 19:00          Qatar       Ecuador      0.3   
1       2       Mon  21-11-2022 16:00        England       IR Iran      2.1   
2       3       Mon  21-11-2022 19:00        Senegal   Netherlands      0.9   
3       4       Mon  21-11-2022 22:00  United States         Wales      0.8   
4       5       Tue  22-11-2022 13:00      Argentina  Saudi Arabia      2.2   
..    ...       ...               ...            ...           ...      ...   
57     58       Fri  09-12-2022 22:00    Netherlands     Argentina      0.6   
58     59       Sat  10-12-2022 18:00        Morocco      Portugal      1.4   
59     60       Sat  10-12-2022 22:00        England        France      2.4   
60     61       Tue  13-12-2022 22:00      Argentina       Croatia      NaN   
61     62       Wed  14-12-2022 22:00         France       Morocco      NaN   

    away_xg        score  attendance                          venue  ...  \
0       1.2          0–2     67372.0                Al Bayt Stadium  ...   
1       1.4          6–2     45334.0  Khalifa International Stadium  ...   
2       0.7          0–2     41721.0             Al Thumama Stadium  ...   
3       1.5          1–1     43418.0          Ahmed bin Ali Stadium  ...   
4       0.1          1–2     88012.0          Lusail Iconic Stadium  ...   
..      ...          ...         ...                            ...  ...   
57      1.9  (3) 2–2 (4)     88235.0          Lusail Iconic Stadium  ...   
58      0.9          1–0     44198.0             Al Thumama Stadium  ...   
59      0.9          1–2     68895.0                Al Bayt Stadium  ...   
60      NaN          NaN         NaN          Lusail Iconic Stadium  ...   
61      NaN          NaN         NaN                Al Bayt Stadium  ...   

   home_offsides away_offsides home_gks away_gks home_throw_ins  \
0            3.0           4.0      4.0      7.0           20.0   
1            2.0           2.0      5.0      5.0           18.0   
2            2.0           1.0      6.0     10.0           17.0   
3            1.0           1.0      5.0     10.0           22.0   
4           10.0           1.0      3.0      9.0           24.0   
..           ...           ...      ...      ...            ...   
57           1.0           2.0      9.0      9.0           29.0   
58           2.0           2.0     12.0      9.0           11.0   
59           1.0           2.0      9.0      5.0           16.0   
60           NaN           NaN      NaN      NaN            NaN   
61           NaN           NaN      NaN      NaN            NaN   

   away_throw_ins home_long_balls  away_long_balls   age  label  
0            17.0            51.0             70.0  20.0     22  
1            17.0            87.0             50.0  20.0     10  
2            28.0            64.0             66.0  30.0     24  
3            25.0            56.0             90.0  40.0     29  
4            13.0            55.0             59.0  25.0      0  
..            ...             ...              ...   ...    ...  
57           19.0            93.0             57.0  28.0     19  
58           27.0            61.0             73.0  28.0     18  
59           14.0            61.0             62.0  28.0     10  
60            NaN             NaN              NaN   NaN      0  
61            NaN             NaN              NaN   NaN     11  

[62 rows x 55 columns]